[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
# actix-web = "4"
reqwest = { version = "0.11", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls",
] }
tokio = { version = "1", features = ["full"] }
