[build]
[target.armv7-unknown-linux-gnueabihf]
linker = "armv7-unknown-linux-gnueabihf-cc"

[registries.crates-io]
protocol = "sparse"

[env]
RUST_LOG = "debug"
# Fill below
SLACK_CHANNEL_ID = ""
SLACK_BOT_USER_OAUTH_TOKEN = ""
GITHUB_USERNAME = ""
GITHUB_ACCESS_TOKEN = ""
