[build]
[target.armv7-unknown-linux-gnueabihf]
linker = "armv7-unknown-linux-gnueabihf-cc"

[env]
RUST_LOG = "debug"
# Fill below
SLACK_CHANNEL_ID = ""
SLACK_BOT_USER_OAUTH_TOKEN = ""
GIT_USERNAME = ""
GIT_ACCESS_TOKEN = ""
