# GitHub Actions で実行できる

name: Daily Summary

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
  SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

jobs:
  cron:
    runs-on: ubuntu-latest

    env:
      TZ: "Asia/Tokyo"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Run
        working-directory: ./target/release
        run: ./notifyer summary-yesterday
