name: Hourly Notification

on:
  schedule:
    - cron: "0 1-23 * * *"
  push:
    branches: ["master", "release"]

jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Tokyo"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "release"
      - name: Build
        run: cargo build --release
      - name: Run
        working-directory: ./target/release
        run: ./playground notify
