name: Cron

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ "master" ]

defaults:
  run:
    working-directory: ./target/release

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        run: ./playground
