name: Cron Job

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Run rust cron
        working-directory: ${{ runner.workspace }}
        run: ./target/release/playground
