name: Hourly Cron

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ "master", "release" ]
    
jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'release'
      - name: Build
        run: cargo build --release
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Japan"
      - name: Run
        working-directory: ./target/release
        run: ./playground
