name: Cron

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ "master" ]
    
jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Run
        working-directory: ./target/release
        run: ./playground
